services:
  - type: web
    name: smart-city-app
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: smart-city-db
          property: connectionString
      - key: JAVA_OPTS
        value: "-Xmx512m -Xms256m"

databases:
  - name: smart-city-db
    plan: free
    databaseName: smartcity
    user: smartcity_user